#!/usr/bin/env sh
export RIAKC_DEPS=/home/rosemary/programming/erlang/riak-erlang-client/deps
export RIAKC=/home/rosemary/programming/erlang/riak-erlang-client
export ERL_LIBS=$ERL_LIBS:/home/rosemary/amqp_client_deps:/home/rosemary/programming/erlang/slv-n-erlang/concurrent/otp/genrs:$RIAKC:$RIAKC_DEPS
