[(load "aggressiveindentccs.el"
       (require 'aggressiveindentccs))
 ,(load "changelogccs.el"
        (require 'changelogccs))
 ,(load "clipboardccs.el"
        (require 'clipboardccs))
 ,(load "codingccs.el"
        (require 'codingccs))
 ,(load "colorthemeccs.el"
        (require 'colorthemeccs))
 ,(load "companyccs.el"
        (require 'companyccs))
 ,(load "confunixccs.el"
        (require 'confunixccs))
 ,(load "cursorccs.el"
        (require 'cursorccs))
 ,(load "diredccs.el"
        (require 'diredccs))
 ,(load "dockerfileccs.el"
        (require 'dockerfileccs))
 ,(load "emacslispccs.el"
        (require 'emacslispccs))
 ,(load "erlccs.el"
        (require 'erlccs))
 ,(load "eshellccs.el"
        (require 'eshellccs))
 ,(load "exccs.el"
        (require 'exccs))
 ,(load "execpathccs.el"
        (require 'execpathccs))
 ,(load "flycheckccs.el"
        (require 'flycheckccs))
 ,(load "flyspellccs.el"
        (require 'flyspellccs))
 ,(load "gitmodesccs.el"
        (require 'gitmodesccs))
 ,(load "groovyccs.el"
        (require 'groovyccs))
 ,(load "highlightchangesccs.el"
        (require 'highlightchangesccs))
 ,(load "highlightparenthesesccs.el"
        (require 'highlightparenthesesccs))
 ,(load "indentationccs.el"
        (require 'indentationccs))
 ,(load "javascriptccs.el"
        (require 'javascriptccs))
 ,(load "jenkinsfileccs.el"
        (require 'jenkinsfileccs))
 ,(load "jsonccs.el"
        (require 'jsonccs))
 ,(load "keybindingsccs.el"
        (require 'keybindingsccs))
 ,(load "latexextraccs.el"
        (require 'latexextraccs))
 ,(load "mdccs.el"
        (require 'mdccs))
 ,(load "projectileccs.el"
        (require 'projectileccs))
 ,(load "pyccs.el"
        (require 'pyccs))
 ,(load "shccs.el"
        (require 'shccs))
 ,(load "smartmodelineccs.el"
        (require 'smartmodelineccs))
 ,(load "swiperccs.el"
        (require 'swiperccs))
 ,(load "webfccs.el"
        (require 'webfccs))
 ,(load "whitespaceccs.el"
        (require 'whitespaceccs))
 ,(load "yamlccs.el"
        (require 'yamlccs))]
